FROM node:lts AS build

# docker build -t willh/ngcli:latest --build-arg CLI_VERSION=1.3.0 -f Dockerfile .
ARG CLI_VERSION

RUN npm install -g @angular/cli@${CLI_VERSION} \
    && ng new demo1 --routing --skip-git \
    && mv demo1 app \
    && rm -rf /root/.npm/

EXPOSE 4200
VOLUME [ "/app" ]

WORKDIR /app
ENTRYPOINT [ "ng", "serve", "--disable-host-check", "--host", "0.0.0.0", "--poll", "1000" ]
